---
title: "2.1 Matching"
author: "Lauke"
date: "05/04/2022"
output: html_document
---

```{r Set seed}
set.seed(123)
```

```{r load in data}
load("~/GitHub/Master_Thesis/Analyses/Workspaces/step1_dat.Rdata")
load("~/GitHub/Master_Thesis/Analyses/Workspaces/prop_scores.Rdata")
```

```{r Libraries}
#require(devtools)
#remotes::install_github("markmfredrickson/optmatch")
library(optmatch) #for optimal full matching algorithm used in MatchIt package
library(MatchIt)
library(haven) #still necessary for working with step1_dat format
```


# a. Match sub-samples based on each of m.iter sets of propensity scores - USING FULLMATCH

```{r Fullmatch}
#apply fullmatch algorithm to each set of propensity scores 
#(sub-step: calculating distance matrices is included in the matchit function)
start_time <- Sys.time()

fullmatches <-
  apply(prop_scores[1:3, ], 1, function(x) {
    matchit(
      group ~ as.factor(Gender) + AGE + GRADE + ISCEDL + ESCS + as.factor(Language),
      distance = x, #input propensity scores here
      method = "full", #fullmatch method
      estimand = "ATE", #use Average Treatment Effect
      include.obj = TRUE, #include output of the call to optmatch::fullmatch in output
      data = step1_dat 
    )
  }) 

end_time <- Sys.time()
```

```{r Outcome and computation time}
summary(fullmatches[[1]])
comptime_fullmatch <- end_time - start_time #5.8 minutes
object.size(fullmatches) #11.5 mB
```

```{r Save fullmatch output}
save(fullmatches, file = "Workspaces/fullmatches.Rdata")
```


### USING PAIR MATCH - run again with ATT now

```{r Optimal pair matching using MatchIt}
gc()
start_time <- Sys.time()

pairmatches <- apply(prop_scores[1:3,], 1, function(x) {matchit(group ~ as.factor(Gender) + AGE + GRADE + ISCEDL + ESCS + as.factor(Language), distance = x, method = "optimal", estimand = "ATT", data = step1_dat)})

end_time <- Sys.time()
```

NB: pairmatch needs ATT/ATC cannot do ATE.

```{r Outcome and computation time}
summary(pairmatches[[1]])
comptime_pairmatch <- end_time - start_time #1.2 hrs
object.size(pairmatches) #13.5 MB
```

```{r Save pairmatch output}
save(pairmatches, file = "Workspaces/pairmatches.Rdata")
```


# b. Create matched data sets - USING FULLMATCH

```{r Creating matches datasets}
#create datasets
fullmatchdat <- lapply(fullmatches, function(x) {match.data(x, group = "all", distance = "prop.score", data = step1_dat, drop.unmatched = T)})

length(unique(fullmatchdat[[1]]$subclass)) #3129 unique subclasses...
```

```{r}
save(fullmatchdat, file = "Workspaces/fullmatchdat.Rdata")
```


#### USING PAIR MATCH

```{r Creating matches datasets}
#create datasets
pairmatchdat <- lapply(pairmatches, function(x) {match.data(x, group = "all", distance = "prop.score", data = step1_dat, drop.unmatched = T)})
```

```{r}
save(pairmatchdat, file = "Workspaces/pairmatchdat.Rdata")
```
