---
title: "2.1b Balance checks"
author: "Lauke"
date: "06/04/2022"
output: html_document
---

```{r}
library(dplyr)
library(haven)
```


```{r check balance stuff}
#NB: run matchit once with method = NULL. en dan de balance stuff.
summary(fullmatches[[1]])
```

Attempt to replicate balance indices:
```{r Balance indices for All Data}
#FOR "ALL DAT": 
mean1 <- as.numeric(fullmatchdat[[1]] %>% filter(group == 0) %>% summarise(mean(AGE)))
mean2 <- as.numeric(fullmatchdat[[1]] %>% filter(group == 1) %>% summarise(mean(AGE)))

var1 <- as.numeric(fullmatchdat[[1]] %>% filter(group == 0) %>% summarise(var(AGE)))
var2 <- as.numeric(fullmatchdat[[1]] %>% filter(group == 1) %>% summarise(var(AGE)))

SMD <- (mean2 - mean1)/sqrt((var1 + var2)/2)
VR <- var2/var1
```

```{r Balance indices for Matched Data}
#write a function that calculated the balance indices for each variable in a matched dataset
SMD_calculator_matched <- function(matched_dataset){
  #calculate weighted means for each variable in dataset by group:
  weighted_means <- matched_dataset %>% group_by(group) %>% summarise(across(where(is.numeric), ~ weighted.mean(.x, w = weights)))
  #calculate variances for each variable in dataset by group:
  grouped_variances <- matched_dataset %>% group_by(group) %>% summarise(across(where(is.numeric), ~var(.x)))
  
  #calculate SMD
  SMD <- (weighted_means[1,] - weighted_means[2,])/sqrt((grouped_variances[1,] + grouped_variances[2,])/2)
  
  #return output
  return(SMD)
}

VR_calculator_matched <- function(matched_dataset){
  #calculate weighted variances for each variable in the dataset BY GROUP separately
  weighted_variances_contr <- matched_dataset %>% filter(group == 0) %>% dplyr::select(where(is.numeric)) %>% cov.wt(., wt = .$weights)
  weighted_variances_treat <- matched_dataset %>% filter(group == 1) %>% dplyr::select(where(is.numeric)) %>% cov.wt(., wt = .$weights)
  
  #calculate VR
  VR <- diag(weighted_variances_treat$cov/weighted_variances_contr$cov)
  
  #return output
  return(VR)
}

#apply both functions to each dataset in the list of datasets: make a big ass data frame for SMD's and VR's to take averages over
#NB: have to do this for fullmatchdat_11, 12, 14 and 15 + the pair match data if necessary
SMDs_matched <- fullmatchdat %>% lapply(., SMD_calculator_matched) %>% do.call(rbind, .) %>% as.data.frame()
VRs_matched  <- fullmatchdat %>% lapply(., VR_calculator_matched)  %>% do.call(rbind, .) %>% as.data.frame()

```

```{r Create table of mean and SE of balance indices per variable DO FOR EACH AGE GROUP}
colMeans(SMDs_matched)

results <- matrix(0, 6, 6)
rownames(results) <- c("Gender", "AGE", "GRADE", "ISCEDL", "ESCS", "Language")
colnames(results) <- c("SMD", "SMD_2.5%", "SMD_97.5%", "VR", "VR_2.5%", "VR_97.5%")

results[,1] <- SMDs_matched %>% dplyr::select(Gender, AGE, GRADE, ISCEDL, ESCS, Language) %>% colMeans()
results[,2] <- SMDs_matched %>% dplyr::select(Gender, AGE, GRADE, ISCEDL, ESCS, Language) %>% apply(., 2, quantile, 0.025)
results[,3] <- SMDs_matched %>% dplyr::select(Gender, AGE, GRADE, ISCEDL, ESCS, Language) %>% apply(., 2, quantile, 0.975)
results[,4] <- VRs_matched  %>% dplyr::select(Gender, AGE, GRADE, ISCEDL, ESCS, Language) %>% colMeans()
results[,2] <- VRs_matched  %>% dplyr::select(Gender, AGE, GRADE, ISCEDL, ESCS, Language) %>% apply(., 2, quantile, 0.025)
results[,2] <- VRs_matched  %>% dplyr::select(Gender, AGE, GRADE, ISCEDL, ESCS, Language) %>% apply(., 2, quantile, 0.975)
```


```{r Check distribution of matched observations per subclass}
classdist <- fullmatchdat[[1]] %>% group_by(subclass) %>% count()

hist(classdist$n)
barplot(height = classdist$n, xlab = "Subclasses", names.arg = classdist$subclass)
barplot(height = classdist$n[classdist$n > 2], names.arg = classdist$subclass[classdist$n > 2])

length(classdist$n[classdist$n > 2]) #633 subclasses with more than 2 matches
length(classdist$n[classdist$n > 3]) #484 with more than 3
```









